
USE [master]
GO

/****** Object:  Database [MealGenieDB]    Script Date: 6/20/2017 3:11:17 PM ******/
CREATE DATABASE [MealGenieDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MealGenieDB', FILENAME = N'C:\Users\Jason\MealGenieDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MealGenieDB_log', FILENAME = N'C:\Users\Jason\MealGenieDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MealGenieDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MealGenieDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MealGenieDB] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [MealGenieDB] SET ANSI_NULLS OFF
GO

ALTER DATABASE [MealGenieDB] SET ANSI_PADDING OFF
GO

ALTER DATABASE [MealGenieDB] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [MealGenieDB] SET ARITHABORT OFF
GO

ALTER DATABASE [MealGenieDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [MealGenieDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [MealGenieDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [MealGenieDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [MealGenieDB] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [MealGenieDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [MealGenieDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [MealGenieDB] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [MealGenieDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [MealGenieDB] SET  DISABLE_BROKER
GO

ALTER DATABASE [MealGenieDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [MealGenieDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [MealGenieDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [MealGenieDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [MealGenieDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [MealGenieDB] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [MealGenieDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [MealGenieDB] SET RECOVERY SIMPLE
GO

ALTER DATABASE [MealGenieDB] SET  MULTI_USER
GO

ALTER DATABASE [MealGenieDB] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [MealGenieDB] SET DB_CHAINING OFF
GO

ALTER DATABASE [MealGenieDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [MealGenieDB] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [MealGenieDB] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [MealGenieDB] SET QUERY_STORE = OFF
GO

USE [MealGenieDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [MealGenieDB]
GO

/****** Object:  Table [dbo].[Ingredient]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Meal]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[MealIngredient]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[MeasurementType]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddIngredient]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddMeal]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetMealById]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetPotentialMeals]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[UpdateIngredient]    Script Date: 6/20/2017 3:11:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [MealGenieDB] SET  READ_WRITE
GO
